kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "graalvm-listdir-pipeline"I
spec:
  source:
    git:
      uri: "https://github.com/petenorth/graalvm-native-image-pipeline.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile