apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  name: spring-boot-maven-ubuntu
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/myproject/spring-boot-maven-ubuntu:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
