apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: spring-boot-maven-ubuntu
  name: spring-boot-maven-ubuntu
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: spring-boot-maven-ubuntu:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/petenorth/graalvm-native-image-pipeline.git
      ref: master
    type: Git
    contextDir: "spring-boot-maven"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile-native
      from:
        kind: DockerImage
        name: petenorth/graal:1.0.0-rc5
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: tTurd9WzEPp1AuXCADAp
    type: GitHub
  - generic:
      secret: xv8jWihF9JNFWc5qj5Fk
    type: Generic
  - type: ConfigChange
status:
  lastVersion: 0
