        pipeline {
            agent {
              node {
                label 'maven'
              }
            }
            stages {
                stage('build') {
                    steps {
                       sh '''
                         mvn clean package
                      ''' 
                    }
                } 
                stage('build image') {
                    steps {
                       sh '''
                         #$GRAALVM_HOME/bin/native-image --no-server -H:+ReportUnsupportedElementsAtRuntime --static -jar target/$(ls target/*.jar)
                         oc start-build graalvm-native-image-ubuntu --from-dir=. --follow
                      '''
                    }
                } 
                stage('run') {
                    steps {
                       sh '''
                         pwd
                         ls -l
                         #time java ListDir $1
                         #time ./listdir $1
                      '''
                    } 
                }
                stage('scratch image build') {
                    steps {
                       sh '''
                         oc start-build graalvm-native-image-scratch --from-dir=. --follow
                      '''
                    } 
                }
            }
        } 
