        pipeline {
            agent {
              node {
                // spin up a graalvm slave pod to run this build on
                label 'graalvm'
              }
            }
            stages {
                stage('build') {
                    steps {
                       sh '''
                         $GRAALVM_HOME/bin/javac ListDir.java
                      ''' 
                    }
                } 
                stage('build image') {
                    steps {
                       sh '''
                         $GRAALVM_HOME/bin/native-image ListDir
                      '''
                    }
                } 
                stage('run') {
                    steps {
                       sh '''
                         pwd
                         ls -l
                         #time java ListDir $1
                         #time ./listdir $1
                      '''
                    } 
                }
                stage('scratch image build') {
                    steps {
                       sh '''
                         oc start-build graalvm-native-image-pipeline --from-dir=. --follow
                      '''
                    } 
                }
            }
        } 
